services:
  postgres:
    image: postgres:18-alpine
    container_name: academic-db-dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  academic-api:
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    container_name: academic-api-app-dev
    command: |
      sh -c "python manage.py migrate --noinput
             python manage.py auto_createsuperuser --username=${DJANGO_SUPERUSER_USERNAME} --password=${DJANGO_SUPERUSER_PASSWORD}
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "9090:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -zv 127.0.0.1 8000"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./api/:/opt/app

  telegram-bot:
    build:
      context: ./tgbot/
      dockerfile: ./Dockerfile
    container_name: telegram-bot-dev
    command: |
      sh -c "npm run dev"
    ports:
      - "9091:3000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "nc -zv 127.0.0.1 3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      academic-api:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./tgbot/src/:/opt/app/src/
      - ./tgbot/nodemon.json:/opt/app/nodemon.json

volumes:
  staticfiles:
  postgres_data:
  session_data:
