services:
  postgres:
    image: postgres:18-alpine
    container_name: academic-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.pg.prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  academic-api:
    image: academic-api:${IMAGE_TAG:-latest}
    container_name: academic-api-app
    command: |
      sh -c "python manage.py collectstatic --noinput
             python manage.py migrate --noinput
             python manage.py auto_createsuperuser --username=${DJANGO_SUPERUSER_USERNAME} --password=${DJANGO_SUPERUSER_PASSWORD}
             python manage.py auto_createtgbotuser --username=${DJANGO_TELEGRAM_BOT_USERNAME} --password=${DJANGO_TELEGRAM_BOT_PASSWORD} --token=${DJANGO_TELEGRAM_BOT_API_TOKEN}
             gunicorn --workers=3 --bind=0.0.0.0:8000 core.wsgi:application"
    env_file:
      - ./.env.academic-api.prod
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -zv 127.0.0.1 8000"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - staticfiles:/opt/app/staticfiles

  telegram-bot:
    image: telegram-bot:${IMAGE_TAG:-latest}
    container_name: telegram-bot-app
    command: |
      sh -c "npm run build && node ./dist/main.js"
    env_file:
      - ./.env.telegram-bot.prod
    depends_on:
      academic-api:
        condition: service_healthy
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: academic-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - staticfiles:/srv/static:ro
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - academic-api

volumes:
  staticfiles:
  postgres_data:
  caddy_data:
  caddy_config:
