- name: Deploy Academic API
  hosts: vps
  become: yes
  vars_files:
    - vars/vault.yml

  tasks:
    - name: Update apt cache and install system dependencies
      apt:
        name:
          - docker.io
          - docker-compose-v2
        state: present
        update_cache: yes

    - name: Create project directory on server
      file:
        path: /opt/app
        state: directory
        owner: developer
        group: developer
        mode: "0755"

    - name: Copy Docker Compose file
      copy:
        src: "{{playbook_dir}}/compose.yml"
        dest: /opt/app/compose.yml

    - name: Copy production environment file from template for postgres
      template:
        src: templates/.env.pg.prod.j2
        dest: /opt/app/.env.pg.prod

    - name: Copy production environment file from template for academic api
      template:
        src: templates/.env.academic-api.prod.j2
        dest: /opt/app/.env.academic-api.prod

    - name: Copy production environment file from template for telegram bot
      template:
        src: templates/.env.telegram-bot.prod.j2
        dest: /opt/app/.env.telegram-bot.prod

    - name: Copy Caddyfile from template
      template:
        src: templates/Caddyfile.j2
        dest: /opt/app/Caddyfile

    - name: Pull required Docker images
      community.docker.docker_image:
        name: "{{item}}"
        source: pull
      loop:
        - "postgres:18-alpine"
        - "caddy:2-alpine"

    - name: Transfer Docker api image archive
      copy:
        src: "{{playbook_dir}}/../../build/academic-api.tar.gz"
        dest: "/opt/app/academic-api.tar.gz"

    - name: Transfer Docker tgbot image archive
      copy:
        src: "{{playbook_dir}}/../../build/telegram-bot.tar.gz"
        dest: "/opt/app/telegram-bot.tar.gz"

    - name: Load Docker api image from archive
      shell: "docker load -i /opt/app/academic-api.tar.gz"
      changed_when: false

    - name: Load Docker tgbot image from archive
      shell: "docker load -i /opt/app/telegram-bot.tar.gz"
      changed_when: false

    - name: Deploy services with Docker Compose
      community.docker.docker_compose_v2:
        project_src: /opt/app
        state: present
        pull: never
        remove_orphans: yes
      environment:
        IMAGE_TAG: "{{ image_tag }}"
        POSTGRES_USER: "{{ POSTGRES_USER }}"
        POSTGRES_DB: "{{ POSTGRES_DB }}"
        POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
        DJANGO_SUPERUSER_USERNAME: "{{ DJANGO_SUPERUSER_USERNAME }}"
        DJANGO_SUPERUSER_PASSWORD: "{{ DJANGO_SUPERUSER_PASSWORD }}"
        DJANGO_TELEGRAM_BOT_USERNAME: "{{ DJANGO_TELEGRAM_BOT_USERNAME }}"
        DJANGO_TELEGRAM_BOT_PASSWORD: "{{ DJANGO_TELEGRAM_BOT_PASSWORD }}"
        DJANGO_TELEGRAM_BOT_API_TOKEN: "{{ DJANGO_TELEGRAM_BOT_API_TOKEN }}"

    - name: Clean up dangling Docker images
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: true
