# Generated by Django 5.2.6 on 2025-10-11 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicDifferenceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_id",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Telegram File ID",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        max_length=1024, verbose_name="Ссылка на файл"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает обработки"),
                            ("PROCESSED", "Обработан"),
                            ("ERROR", "Ошибка обработки"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="difference_files",
                        to="api.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "файл с расхождениями",
                "verbose_name_plural": "файлы с расхождениями",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAcademicDifferenceFile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True,
                        blank=True,
                        db_index=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False),
                ),
                (
                    "file_id",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Telegram File ID",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        max_length=1024, verbose_name="Ссылка на файл"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает обработки"),
                            ("PROCESSED", "Обработан"),
                            ("ERROR", "Ошибка обработки"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                (
                    "history_change_reason",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "history_type",
                    models.CharField(
                        choices=[
                            ("+", "Created"),
                            ("~", "Changed"),
                            ("-", "Deleted"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="api.student",
                        verbose_name="Студент",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical файл с расхождениями",
                "verbose_name_plural": "historical файлы с расхождениями",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
