# Generated by Django 5.2.6 on 2025-12-18 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_academicdifferencefile_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicdifference",
            options={"verbose_name": "РУП", "verbose_name_plural": "РУПы"},
        ),
        migrations.AlterModelOptions(
            name="academicdifferencefile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Файл с РУП",
                "verbose_name_plural": "Файлы с РУПами",
            },
        ),
        migrations.AlterModelOptions(
            name="academicgroup",
            options={"verbose_name": "Группа", "verbose_name_plural": "Группы"},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Кафедра",
                "verbose_name_plural": "Кафедры",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalacademicdifference",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical РУП",
                "verbose_name_plural": "historical РУПы",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalacademicdifferencefile",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Файл с РУП",
                "verbose_name_plural": "historical Файлы с РУПами",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalacademicgroup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Группа",
                "verbose_name_plural": "historical Группы",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaldepartment",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Кафедра",
                "verbose_name_plural": "historical Кафедры",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalstudent",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Студент",
                "verbose_name_plural": "historical Студенты",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalsubject",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Предмет",
                "verbose_name_plural": "historical Предметы",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalteacher",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Преподаватель",
                "verbose_name_plural": "historical Преподаватели",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "verbose_name": "Студент",
                "verbose_name_plural": "Студенты",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "verbose_name": "Преподаватель",
                "verbose_name_plural": "Преподаватели",
            },
        ),
        migrations.AddField(
            model_name="academicdifferencefile",
            name="name",
            field=models.CharField(
                default="Не указано",
                max_length=255,
                verbose_name="Название файла",
            ),
        ),
        migrations.AddField(
            model_name="historicalacademicdifferencefile",
            name="name",
            field=models.CharField(
                default="Не указано",
                max_length=255,
                verbose_name="Название файла",
            ),
        ),
        migrations.AlterField(
            model_name="academicdifference",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="academicdifference",
            name="deadline",
            field=models.DateField(verbose_name="Дедлайн"),
        ),
        migrations.AlterField(
            model_name="academicdifference",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="Сдано"),
        ),
        migrations.AlterField(
            model_name="academicdifference",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="api.student",
                verbose_name="Студент",
            ),
        ),
        migrations.AlterField(
            model_name="academicdifference",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="api.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="academicdifference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="academicdifferencefile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="academicdifferencefile",
            name="state",
            field=models.CharField(
                choices=[
                    ("APPROVED", "Подтверждён"),
                    ("NOT_ACCEPTED", "Не принят"),
                    ("REVIEW", "Рассмотрение"),
                ],
                db_index=True,
                default="REVIEW",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="academicdifferencefile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="academicgroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="academicgroup",
            name="number",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Номер группы"
            ),
        ),
        migrations.AlterField(
            model_name="academicgroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="department",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="historicalacademicdifference",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="historicalacademicdifference",
            name="deadline",
            field=models.DateField(verbose_name="Дедлайн"),
        ),
        migrations.AlterField(
            model_name="historicalacademicdifference",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="Сдано"),
        ),
        migrations.AlterField(
            model_name="historicalacademicdifference",
            name="student",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="api.student",
                verbose_name="Студент",
            ),
        ),
        migrations.AlterField(
            model_name="historicalacademicdifference",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="api.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="historicalacademicdifference",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Обновлен"
            ),
        ),
        migrations.AlterField(
            model_name="historicalacademicdifferencefile",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="historicalacademicdifferencefile",
            name="state",
            field=models.CharField(
                choices=[
                    ("APPROVED", "Подтверждён"),
                    ("NOT_ACCEPTED", "Не принят"),
                    ("REVIEW", "Рассмотрение"),
                ],
                db_index=True,
                default="REVIEW",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="historicalacademicdifferencefile",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Обновлен"
            ),
        ),
        migrations.AlterField(
            model_name="historicalacademicgroup",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="historicalacademicgroup",
            name="number",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Номер группы"
            ),
        ),
        migrations.AlterField(
            model_name="historicalacademicgroup",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Обновлен"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldepartment",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldepartment",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="historicaldepartment",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Обновлен"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudent",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudent",
            name="group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="api.academicgroup",
                verbose_name="Связанная группа",
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudent",
            name="settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Настройки"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudent",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Обновлен"
            ),
        ),
        migrations.AlterField(
            model_name="historicalstudent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Связанный пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubject",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubject",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="api.department",
                verbose_name="Кафедра",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubject",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubject",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Обновлен"
            ),
        ),
        migrations.AlterField(
            model_name="historicalteacher",
            name="created_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="historicalteacher",
            name="updated_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Обновлен"
            ),
        ),
        migrations.AlterField(
            model_name="historicalteacher",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="api.academicgroup",
                verbose_name="Связанная группа",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Настройки"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Связанный пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="api.department",
                verbose_name="Кафедра",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subjects",
            field=models.ManyToManyField(
                to="api.subject", verbose_name="Предмет преподавателя"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, verbose_name="Отчество"),
        ),
    ]
