name: Python CI Pipeline

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]

jobs:
  lint-commits:
    name: Lint Commit Messages
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Commitizen
        run: pip install commitizen

      - name: Lint commit messages
        if: github.event_name == 'pull_request'
        run: cz check --rev-range ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}

  build-and-test:
    runs-on: ubuntu-22.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: academic_user_dev
          POSTGRES_PASSWORD: academic_user_dev
          POSTGRES_DB: academic_db_dev
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linters
        env:
          SECRET_KEY: "dummy-secret-key-for-linting"
          DEBUG: "True"
          ALLOWED_HOSTS: "localhost"
          POSTGRES_USER: academic_user_dev
          POSTGRES_DB: academic_db_dev
          POSTGRES_PASSWORD: academic_user_dev
          POSTGRES_PORT: 5432
          POSTGRES_HOST: localhost
        run: |
          cd api
          black --check .
          isort --check-only .
          pylint api/ core/

      - name: Run tests with coverage
        env:
          SECRET_KEY: "dummy-secret-key-for-linting"
          DEBUG: "True"
          ALLOWED_HOSTS: localhost
          POSTGRES_USER: academic_user_dev
          POSTGRES_DB: academic_db_dev
          POSTGRES_PASSWORD: academic_user_dev
          POSTGRES_PORT: 5432
          POSTGRES_HOST: localhost
        run: |
          cd api
          pytest --cov=api --cov-report=term-missing
